name: Build with Nuitka on Windows

# on: 
#   push:

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3 # Aktualisiert auf v3
    - name: Set up Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install base58==2.1.1 cryptography==3.4.8 mnemonic==0.21 PySide6==6.6.1 PySide6_Addons==6.6.1 PySide6_Essentials==6.6.1 shiboken6==6.6.1

    - name: Compile with Nuitka
      run: |
        python -m nuitka --output-filename=eMinuto --output-dir=${{ github.workspace }}\eMinuto --follow-imports --include-module=mnemonic --enable-plugin=pyside6 --standalone main_qt.py
